stages:
  acquire:
    cmd: python src/acquisition.py
    deps:
      - src/acquisition.py
    outs:
      - data/raw/train.csv

  prepare:
    cmd: python src/preparation.py
    deps:
      - src/preparation.py
      - data/raw/train.csv
    outs:
      - data/processed/train_processed.csv

  train:
    cmd: python src/modeling.py
    deps:
      - src/modeling.py
      - data/processed/train_processed.csv
    outs:
      - models/model.pkl
      - models/scaler.pkl
      - models/encoder.pkl

  evaluate:
    cmd: python src/evaluation.py
    deps:
      - src/evaluation.py
      - models/model.pkl
      - data/processed/train_processed.csv
    outs:
      - logs/evaluation.log
