name: CI/CD Pipeline for Titanic Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Cache dependencies
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Set up DVC
      - name: Set up DVC
        run: |
          dvc pull
          dvc repro

  test-and-train:
    runs-on: ubuntu-latest
    needs: setup-environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Run DVC pipeline for training
      - name: Run DVC Pipeline
        run: |
          dvc repro train

      # Evaluate Model
      - name: Evaluate Model
        run: |
          python src/evaluation.py

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test-and-train

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t titanic-pipeline .

      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker tag titanic-pipeline:latest ${{ secrets.DOCKER_USERNAME }}/titanic-pipeline:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/titanic-pipeline:latest

      # Deploy Docker Container
      - name: Deploy Docker Container
        run: |
          docker run -d -p 8501:8501 ${{ secrets.DOCKER_USERNAME }}/titanic-pipeline:latest
